name: "HA Addon Template"
version: "2.0.0"
slug: "ha_addon_template"
description: "Template repo for a HA Addon."
url: https://github.com/Silveira26/ha-addon-template
arch:
  - amd64
  - armv7
  - aarch64
startup: "application"
init: "false"
boot: "auto"
options:
  log_message: "Hello from the addon!"
schema:
  log_message: "str"
image: "ghcr.io/silveira26/ha-addon-template-{arch}"
