name: "Build and Release Add-on"

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Extract version from config.yaml
        id: get_version
        run: |
          # Extract the version string from config.yaml
          # This assumes the version line is like: version: "2.0.0"
          VERSION=$(grep '^version:' config.yaml | sed 's/version: *"//; s/"//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version is ${VERSION}"

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push multi-arch images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ env.REPO_NAME }}-amd64:${{ env.VERSION }}
            ghcr.io/${{ env.REPO_NAME }}-armv7:${{ env.VERSION }}
            ghcr.io/${{ env.REPO_NAME }}-aarch64:${{ env.VERSION }}
            ghcr.io/${{ env.REPO_NAME }}:${{ env.VERSION }}
